### ISSUE TITLE
Improve fault tolerance/error recovery capabilities.

### ISSUE THREAD

**Issue by bd82** [jacobp100/json-view#1]
I saw your post on r/javascript but replying here to avoid thread hijacking/self promotion...

When given an invalid JSON the "half" until the error will still be rendered correctly.
(by using json-half-parse).

**What about integrating stronger error recovery/fault tolerance capabilities ?**
**_shameless plug**_ :smile:   : Checkout A parsing library that I authored:

http://sap.github.io/chevrotain/playground/
The first example there implements a JSON parser with stronger error recovery capabilities.
This can allow you to display **most** of the invalid JSON instead of just the part before the error.

Same example using ES6 syntax:
https://github.com/SAP/chevrotain/blob/master/examples/nodejs/jsonParserES6.js

**Comment by jacobp100** [comment]
Looks neat, but doesn't meet the goals of half-parse. Thanks anyway!
